# for local development
version: '3.7'
services:
  todo-backend:
    container_name: todo_backend
    build:
      context: .
    working_dir: /app
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    command: pipenv run python manage.py runserver 0:8000
    networks:
      - swarm
networks:
  swarm:
    driver: "bridge"
    name: "swarm"
